# Eat Safe, Love

## Notebook Set Up

In [3]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint

In [4]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [5]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [6]:
# review the collections in our database
collections = db.list_collection_names()

In [7]:
# assign the collection to a variable
establishments = db['establishments']

In [8]:
pprint(collections)

['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. which establishments have a hygiene score equal to 20?

In [9]:
# Find establishments with a hygiene score equal to 20
query = {"scores.Hygiene": 20}
results = establishments.find(query)

# Use a loop to count the documents in the result
count = 0
for _ in results:
    count += 1

print("Number of documents with hygiene score equal to 20:", count)

# Display the first document in the results using pprint
if count > 0:
    # You'll need to create a new cursor since the previous one is exhausted
    first_document = establishments.find(query)[0]
    pprint(first_document)
else:
    print("No establishments with a hygiene score of 20 found.")

Number of documents with hygiene score equal to 20: 41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6507c77c83e8ddace47c8005'),
 'geocode': {'latitude': '50.769705', 'longitude': '0.27694'},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [10]:
import pandas as pd

# Convert the result to a Pandas DataFrame 
query = {"scores.Hygiene": 20}
results = establishments.find(query)
df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
num_rows = len(df)
print(f"Number of rows in the DataFrame: {num_rows}")

# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(df.head(10))

Number of rows in the DataFrame: 41
First 10 rows of the DataFrame:
                        _id   FHRSID  ChangesByServerID  \
0  6507c77c83e8ddace47c8005   110681                  0
1  6507c77c83e8ddace47c8386   612039                  0
2  6507c77c83e8ddace47c8690   730933                  0
3  6507c77c83e8ddace47c887e   172735                  0
4  6507c77c83e8ddace47c888d   172953                  0
5  6507c77d83e8ddace47c922c   512854                  0
6  6507c77d83e8ddace47c944d  1537089                  0
7  6507c77e83e8ddace47ca978   155648                  0
8  6507c77f83e8ddace47cadbc  1012883                  0
9  6507c77f83e8ddace47cb5ce   644109                  0

  LocalAuthorityBusinessID               BusinessName  \
0                     4029        The Chase Rest Home
1                1970/FOOD                 Brenalwood
2                1698/FOOD              Melrose Hotel
3             PI/000023858              Seaford Pizza
4             PI/000024532              Golden Palace
5            12/00816/BUTH           Ashby's Butchers
6          22/00224/RESTUN  South Sea Express Cuisine
7              EH/00006058              Golden Palace
8         17/00110/MIXED/S             The Tulip Tree
9                    41811                      F & S

                        BusinessType  BusinessTypeID           AddressLine1  \
0                    Caring Premises               5   5-6 Southfields Road
1                    Caring Premises               5              Hall Lane
2  Hotel/bed & breakfast/guest house            7842  53 Marine Parade East
3             Takeaway/sandwich shop            7844          4 High Street
4            Restaurant/Cafe/Canteen               1         5 South Street
5                  Retailers - other            4613   777 Southchurch Road
6            Restaurant/Cafe/Canteen               1    33 Alexandra Street
7             Takeaway/sandwich shop            7844          7 London Road
8            Restaurant/Cafe/Canteen               1          3 The Village
9                  Retailers - other            4613

         AddressLine2 AddressLine3  ...  \
0          Eastbourne  East Sussex  ...
1  Walton-on-the-Naze        Essex  ...
2      Clacton On Sea        Essex  ...
3             Seaford  East Sussex  ...
4             Seaford  East Sussex  ...
5     Southend-On-Sea        Essex  ...
6     Southend-on-sea        Essex  ...
7            Rayleigh        Essex  ...
8       Chiddingstone         KENT  ...
9      81 Southernhay     Basildon  ...

                      LocalAuthorityWebSite  \
0  http://www.eastbourne.gov.uk/foodratings
1             http://www.tendringdc.gov.uk/
2             http://www.tendringdc.gov.uk/
3       http://www.lewes-eastbourne.gov.uk/
4       http://www.lewes-eastbourne.gov.uk/
5                http://www.southend.gov.uk
6                http://www.southend.gov.uk
7                http://www.rochford.gov.uk
8              http://www.sevenoaks.gov.uk/
9                http://www.basildon.gov.uk

              LocalAuthorityEmailAddress  \
0        Customerfirst@eastbourne.gov.uk
1             fhsadmin@tendringdc.gov.uk
2             fhsadmin@tendringdc.gov.uk
3    ehealth.ldc@lewes-eastbourne.gov.uk
4    ehealth.ldc@lewes-eastbourne.gov.uk
5    EnvironmentalHealth@southend.gov.uk
6    EnvironmentalHealth@southend.gov.uk
7       customerservices@rochford.gov.uk
8  environmental.health@sevenoaks.gov.uk
9                    ehs@basildon.gov.uk

                                              scores SchemeType  \
0  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
1  {'Hygiene': 20, 'Structural': 15, 'ConfidenceI...       FHRS
2  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
3  {'Hygiene': 20, 'Structural': 10, 'ConfidenceI...       FHRS
4  {'Hygiene': 20, 'Structural': 10, 'ConfidenceI...       FHRS
5  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
6  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
7  {'Hygiene': 20, 'Structural': 15, 'ConfidenceI...       FHRS
8  {'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...       FHRS
9  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS

                                             geocode RightToReply  \
0  {'longitude': '0.27694', 'latitude': '50.769705'}
1  {'longitude': '1.278721', 'latitude': '51.8575...
2  {'longitude': '1.15927', 'latitude': '51.789429'}
3  {'longitude': '0.10202', 'latitude': '50.770885'}
4  {'longitude': '0.101446', 'latitude': '50.7707...
5  {'longitude': '0.736349', 'latitude': '51.5414...
6  {'longitude': '0.7121671', 'latitude': '51.535...
7  {'longitude': '0.602364', 'latitude': '51.5915...
8  {'longitude': '0.146449998021126', 'latitude':...
9  {'longitude': '0.462307', 'latitude': '51.57005'}

      Distance NewRatingPending  \
0  4613.888288            False
1  4617.965824            False
2  4619.656144            False
3  4620.421725            False
4  4620.437179            False
5  4625.565258            False
6  4626.200132            False
7  4632.276890            False
8  4633.934041            False
9  4636.552523            False

                                                meta  \
0  {'dataSource': None, 'extractDate': '0001-01-0...
1  {'dataSource': None, 'extractDate': '0001-01-0...
2  {'dataSource': None, 'extractDate': '0001-01-0...
3  {'dataSource': None, 'extractDate': '0001-01-0...
4  {'dataSource': None, 'extractDate': '0001-01-0...
5  {'dataSource': None, 'extractDate': '0001-01-0...
6  {'dataSource': None, 'extractDate': '0001-01-0...
7  {'dataSource': None, 'extractDate': '0001-01-0...
8  {'dataSource': None, 'extractDate': '0001-01-0...
9  {'dataSource': None, 'extractDate': '0001-01-0...

                                               links
0  [{'rel': 'self', 'href': 'https://api.ratings....
1  [{'rel': 'self', 'href': 'https://api.ratings....
2  [{'rel': 'self', 'href': 'https://api.ratings....
3  [{'rel': 'self', 'href': 'https://api.ratings....
4  [{'rel': 'self', 'href': 'https://api.ratings....
5  [{'rel': 'self', 'href': 'https://api.ratings....
6  [{'rel': 'self', 'href': 'https://api.ratings....
7  [{'rel': 'self', 'href': 'http://api.ratings.f...
8  [{'rel': 'self', 'href': 'http://api.ratings.f...
9  [{'rel': 'self', 'href': 'http://api.ratings.f...

[10 rows x 28 columns]

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [15]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {
    "AddressLine4": "London",
    "RatingValue": {"$gte": "4"}
}
# Find establishments that match the query
#results = establishments.find(query)

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print("Number of establishments in London with a rating of 4 or higher:", count)

# Display the first document in the results using pprint
if count > 0:
    first_document = establishments.find_one(query)
    pprint(first_document)
else:
    print("No establishments in London with a rating of 4 or higher found.")

Number of establishments in London with a rating of 4 or higher: 437
{'AddressLine1': '16 Muir Road',
 'AddressLine2': '',
 'AddressLine3': 'Hackney',
 'AddressLine4': 'London',
 'BusinessName': 'The Vegan Honey LTD',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4623.064947758399,
 'FHRSID': 1371765,
 'LocalAuthorityBusinessID': 'HAC0616',
 'LocalAuthorityCode': '512',
 'LocalAuthorityEmailAddress': 'technicalbusinesssupport@hackney.gov.uk',
 'LocalAuthorityName': 'Hackney',
 'LocalAuthorityWebSite': 'http://www.hackney.gov.uk/e-env-environmental-health.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME15 6PX',
 'RatingDate': '1901-01-01T00:00:00',
 'RatingKey': 'fhrs_awaitinginspection_en-gb',
 'RatingValue': 'AwaitingInspection',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6507c77d83e8ddace47c8cbf'),
 'geocode': {'latitude': '51.2666282653809', 'longitude': '0.524308979511261'},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1371765',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': None,
            'Hygiene': None,
            'Structural': None}}

In [16]:
# Convert the result to a Pandas DataFrame
results = establishments.find(query)
df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
num_rows = len(df)
print(f"Number of rows in the DataFrame: {num_rows}")

# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(df.head(10))

Number of rows in the DataFrame: 437
First 10 rows of the DataFrame:
                        _id   FHRSID  ChangesByServerID  \
0  6507c77d83e8ddace47c8cbf  1371765                  0
1  6507c78183e8ddace47cd4b7  1049722                  0
2  6507c78183e8ddace47cd4d8  1261451                  0
3  6507c78183e8ddace47cd4dd   987733                  0
4  6507c78183e8ddace47cd4de   357627                  0
5  6507c78183e8ddace47cd4fb  1151706                  0
6  6507c78183e8ddace47cd4ff  1468037                  0
7  6507c78183e8ddace47cd500   358232                  0
8  6507c78183e8ddace47cd50a  1415217                  0
9  6507c78183e8ddace47cd51d   635108                  0

  LocalAuthorityBusinessID                                       BusinessName  \
0                  HAC0616                                The Vegan Honey LTD
1              18/00096/CP                                 The Mezzanine Cafe
2           20/00255/MIXED  St Edward's Church, Mottingham - StEP Lunch Cl...
3           16/00340/MIXED                             Maryfield Pre-School 2
4         00000/0000/8/951                                              Co-op
5         00000/0000/8/204               North Hub @ Castlecombe Youth Centre
6           22/00180/MIXED                                           Spencers
7           02/00010/MIXED                                     Domino's Pizza
8           21/00630/MIXED                                  Papa John's Pizza
9           14/00056/MIXED                                       Perfect Cafe

                            BusinessType  BusinessTypeID  \
0                Other catering premises            7841
1                Restaurant/Cafe/Canteen               1
2                Other catering premises            7841
3                        Caring Premises               5
4  Retailers - supermarkets/hypermarkets            7840
5                        Caring Premises               5
6                      Retailers - other            4613
7                 Takeaway/sandwich shop            7844
8                 Takeaway/sandwich shop            7844
9                Restaurant/Cafe/Canteen               1

                  AddressLine1         AddressLine2    AddressLine3  ...  \
0                 16 Muir Road                              Hackney  ...
1                       Arch D  The Link Thamesmead  Bazalgette Way  ...
2       St Edwards Church Hall      St Keverne Road      Mottingham  ...
3  Mottingham Community Centre      Kimmeridge Road      Mottingham  ...
4        The Co-operative Food      Kimmeridge Road      Mottingham  ...
5     Castlecombe Youth Centre     Castlecombe Road      Mottingham  ...
6            11 Cranley Parade      Kimmeridge Road      Mottingham  ...
7             3 Cranley Parade    Beaconsfield Road      Mottingham  ...
8             4 Cranley Parade    Beaconsfield Road      Mottingham  ...
9       11 Beaconsfield Parade    Beaconsfield Road      Mottingham  ...

                               LocalAuthorityWebSite  \
0  http://www.hackney.gov.uk/e-env-environmental-...
1                           http://www.bexley.gov.uk
2                          http://www.bromley.gov.uk
3                          http://www.bromley.gov.uk
4                          http://www.bromley.gov.uk
5                          http://www.bromley.gov.uk
6                          http://www.bromley.gov.uk
7                          http://www.bromley.gov.uk
8                          http://www.bromley.gov.uk
9                          http://www.bromley.gov.uk

                LocalAuthorityEmailAddress  \
0  technicalbusinesssupport@hackney.gov.uk
1                food.safety@bexley.gov.uk
2                      food@bromley.gov.uk
3                      food@bromley.gov.uk
4                      food@bromley.gov.uk
5                      food@bromley.gov.uk
6                      food@bromley.gov.uk
7                      food@bromley.gov.uk
8                      food@bromley.gov.uk
9                      food@bromley.gov.uk

                                              scores SchemeType  \
0  {'Hygiene': None, 'Structural': None, 'Confide...       FHRS
1  {'Hygiene': 10, 'Structural': 0, 'ConfidenceIn...       FHRS
2  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
3  {'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...       FHRS
4  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
5  {'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...       FHRS
6  {'Hygiene': 0, 'Structural': 10, 'ConfidenceIn...       FHRS
7  {'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...       FHRS
8  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
9  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS

                                             geocode RightToReply  \
0  {'longitude': '0.524308979511261', 'latitude':...
1  {'longitude': '0.121751002967358', 'latitude':...
2  {'longitude': '0.04774', 'latitude': '51.428019'}
3  {'longitude': '0.0465259999036789', 'latitude'...
4  {'longitude': '0.0465259999036789', 'latitude'...
5  {'longitude': '0.0433179996907711', 'latitude'...
6  {'longitude': '0.046141', 'latitude': '51.4273...
7  {'longitude': '0.046141', 'latitude': '51.4273...
8  {'longitude': '0.0460971', 'latitude': '51.427...
9  {'longitude': '0.045445', 'latitude': '51.4271...

      Distance NewRatingPending  \
0  4623.064948            False
1  4646.357884            False
2  4646.410908            False
3  4646.414831            False
4  4646.414831            False
5  4646.439635            False
6  4646.443677            False
7  4646.443677            False
8  4646.448256            False
9  4646.464277            False

                                                meta  \
0  {'dataSource': None, 'extractDate': '0001-01-0...
1  {'dataSource': None, 'extractDate': '0001-01-0...
2  {'dataSource': None, 'extractDate': '0001-01-0...
3  {'dataSource': None, 'extractDate': '0001-01-0...
4  {'dataSource': None, 'extractDate': '0001-01-0...
5  {'dataSource': None, 'extractDate': '0001-01-0...
6  {'dataSource': None, 'extractDate': '0001-01-0...
7  {'dataSource': None, 'extractDate': '0001-01-0...
8  {'dataSource': None, 'extractDate': '0001-01-0...
9  {'dataSource': None, 'extractDate': '0001-01-0...

                                               links
0  [{'rel': 'self', 'href': 'https://api.ratings....
1  [{'rel': 'self', 'href': 'http://api.ratings.f...
2  [{'rel': 'self', 'href': 'http://api.ratings.f...
3  [{'rel': 'self', 'href': 'http://api.ratings.f...
4  [{'rel': 'self', 'href': 'http://api.ratings.f...
5  [{'rel': 'self', 'href': 'http://api.ratings.f...
6  [{'rel': 'self', 'href': 'http://api.ratings.f...
7  [{'rel': 'self', 'href': 'http://api.ratings.f...
8  [{'rel': 'self', 'href': 'http://api.ratings.f...
9  [{'rel': 'self', 'href': 'http://api.ratings.f...

[10 rows x 28 columns]

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [40]:
# Define the name of the restaurant to search for
restaurant_name = "Penang Flavours"

# Define the query to find the restaurant by name
query = {"BusinessName": restaurant_name}

# Use find_one to search for the restaurant
restaurant = establishments.find_one(query)

# Check if the restaurant was found
if restaurant:
    print(f"{restaurant_name} is in the dataset.")
    # Optionally, you can print the details of the restaurant
    print("Restaurant Details:")
    pprint(restaurant)
else:
    print(f"{restaurant_name} is not in the dataset.")

Penang Flavours is in the dataset.
Restaurant Details:
{'AddressLine1': 'Penang Flavours',
 'AddressLine2': '146A Plumstead Rd',
 'AddressLine3': 'London',
 'AddressLine4': '',
 'BusinessName': 'Penang Flavours',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 'YourCorrectBusinessTypeIDHere',
 'Distance': 4623.972328074718,
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': True,
 'Phone': '',
 'PostCode': 'SE18 7DY',
 'RatingValue': None,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('650e5712816915c8007b659a'),
 'geocode': {'latitude': '51.49014200', 'longitude': '0.08384000'},
 'scores': {'ConfidenceInManagement': '', 'Hygiene': '', 'Structural': ''}}

In [47]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = float("0.01")
latitude = float("51.49014200") 
longitude = float("0.08384000")

query = {
    "geocode.latitude": {
        "$gte": latitude - degree_search,
        "$lte": latitude + degree_search
    },
    "geocode.longitude": {
        "$gte": longitude - degree_search,
        "$lte": longitude + degree_search
    },
    "RatingValue": 5
}

sort = [("scores.Hygiene", 1)]

# Use find method to retrieve the top 5 establishments that match the criteria
results = establishments.find(query).sort(sort).limit(5)

# Print the results
print("Top 5 establishments with RatingValue 5, sorted by lowest hygiene score:")
for idx, establishment in enumerate(results, start=1):
    print(f"{idx}. Name: {establishment['BusinessName']}, Hygiene Score: {establishment['scores:','Hygiene']}")

Top 5 establishments with RatingValue 5, sorted by lowest hygiene score:

In [48]:
# Convert result to Pandas DataFrame
# Create an empty list to store the documents
document_list = []

# Iterate through the MongoDB query results and append each document to the list
for establishment in results:
    document_list.append(establishment)

# Create a Pandas DataFrame from the list of documents
df = pd.DataFrame(document_list)

# Display the Pandas DataFrame
print("Pandas DataFrame:")
print(df)

Pandas DataFrame:
Empty DataFrame
Columns: []
Index: []

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [49]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
pipeline = [
    {
        "$match": {
            "scores.Hygiene": 0
        }
    },
    {
        "$group": {
            "_id": "$LocalAuthorityName",
            "count": {"$sum": 1}
        }
    },
    {
        "$sort": {"count": -1}
    }
]
#Execute the aggregation pipeline
result = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print("Number of documents in the result:", len(result))
# Print the first 10 results
print("First 10 results:")
pprint(result[:10])

Number of documents in the result: 55
First 10 results:
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [51]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(result)
# Display the number of rows in the DataFrame
num_rows = len(df)
print(f"Number of rows in the DataFrame: {num_rows}")
# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
df.head(10)

Number of rows in the DataFrame: 55
First 10 rows of the DataFrame:

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542